version: '2.4'

################################################################################
#
# EXAMPLE FILE:
# This docker-compose file contains example services for LND and LTC. This
# file can be used directly to setup your application for use w/ the lnd-engine.
#
# IMPORTANT NOTES:
# - Available ports for a specific service are located in its applicable Dockerfile.
#   However, nothing is bound to the host
# - All cert generation happens within the Dockerfiles
# - /shared directory is used between local services for sharing of public keys
#   however in a production setting, this setup would need to change
#
# The official LND docker setup can be found here:
# https://github.com/lightningnetwork/lnd/tree/master/docker
#
################################################################################

services:
  ltcd:
    image: kinesis_ltcd:latest
    volumes:
      - shared:/shared
      - litecoin:/data
    environment:
      - RPC_USER=kuser
      - RPC_PASS=kpass
      - NETWORK=simnet
      - DEBUG=info
      - DATA_DIR=/data
      - LOG_DIR=/data
      - RPC_KEY=/secure/rpc-ltc.key
      - RPC_CERT=/shared/rpc-ltc.cert
      - RPC_LISTEN=0.0.0.0
      # This is set dynamically in the startup scripts
      # TODO: figure out how to dynamically set this variable and prevent it from
      # triggering warnings
      - "MINING_ADDRESS=$MINING_ADDRESS"
    networks:
      - lnd
    entrypoint: ["./start-ltcd.sh"]

  lnd_ltc:
    image: kinesis_lnd:latest
    environment:
      - RPC_USER=kuser
      - RPC_PASS=kpass
      - RPC_HOST=ltcd
      - RPC_CERT_PATH=/shared/rpc-ltc.cert
      - ADMIN_MACAROON=/shared/lnd-engine-admin-ltc.macaroon
      - READ_ONLY_MACAROON=/shared/lnd-engine-readonly-ltc.macaroon
      - INVOICE_MACAROON=/shared/lnd-engine-invoice-ltc.macaroon
      - TLS_CERT_PATH=/shared/lnd-engine-tls-ltc.cert
      - TLS_KEY_PATH=/secure/lnd-engine-tls-ltc.key
      - NETWORK=simnet
      - CHAIN=litecoin
      - NODE=ltcd
      - DEBUG=info
      - RPC_LISTEN=0.0.0.0:10009
      - LISTEN=0.0.0.0:10111
      # This address is for development only. You must change this to a
      # tld to use in a production setting
      - EXTERNAL_ADDRESS=docker.for.mac.host.internal:10111
      - REST_LISTEN=0.0.0.0:8101
      - DATA_DIR=/data
      - LOG_DIR=/data
    networks:
      - lnd
    volumes:
      - 'shared:/shared'
      - 'lnd:/data'
    # Please refer to the lnd docker file for details on exposed ports
    # ports:
    #   - '10111:10111'
    entrypoint: ["./start-lnd.sh"]

volumes:
  shared:
  litecoin:
  lnd:

networks:
  lnd:
